from pathlib import Path
import rasterio  # already installed

# Root of your project
PROJECT_ROOT = Path(r"G:\GIS_AI_PROJECT")

# Folder where all training GeoTIFFs live
GEOTIFF_DIR = PROJECT_ROOT / "data" / "intermediate" / "geotiff"

# Thresholds (you can adjust these)

# Thresholds tuned for your machine
# Total pixels above this will be flagged as "large"
PIXEL_THRESHOLD = 6.0 * 1024**3   # ~6 billion pixels (same as 6 GiB for uint8)

# Approx. RAM needed for uint8 mask above this (GiB) will be flagged
MASK_RAM_THRESHOLD_GIB = 6.0      # 6 GiB

def main():
    print(f"Scanning GeoTIFFs under: {GEOTIFF_DIR}\n")

    if not GEOTIFF_DIR.exists():
        print("GeoTIFF folder does not exist.")
        return

    any_found = False

    for tif in GEOTIFF_DIR.rglob("*.tif"):
        # Skip mask files generated by our script
        if tif.name.upper().endswith("_MASK.TIF"):
            continue

        any_found = True
        try:
            with rasterio.open(tif) as src:
                width, height = src.width, src.height  # raster size[web:213]
        except Exception as e:
            print(f"{tif.name:70s}  ERROR opening file: {e}")
            continue

        pixels = width * height
        # uint8 mask: 1 byte per pixel
        bytes_mask = pixels
        gib_mask = bytes_mask / (1024**3)

        flags = []
        if pixels > PIXEL_THRESHOLD:
            flags.append("MANY_PIXELS")
        if gib_mask > MASK_RAM_THRESHOLD_GIB:
            flags.append("MASK_RAM_HIGH")

        flag_str = ", ".join(flags) if flags else "OK"

        print(
            f"{tif.name:70s}  "
            f"{width:7d} x {height:<7d}  "
            f"{pixels/1e6:7.1f} Mpx  "
            f"mask≈{gib_mask:5.2f} GiB  "
            f"{flag_str}"
        )

    if not any_found:
        print("No .tif files found (excluding *_mask.tif).")


if __name__ == "__main__":
    main()
